{"name": "用户登录--预期失败--用例二", "status": "passed", "attachments": [{"name": "log", "source": "9da0c768-58e4-4101-b5f3-840e16ae38d1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'11111'"}, {"name": "password", "value": "''"}, {"name": "expect_alert", "value": "['请输入密码']"}], "start": 1678676434704, "stop": 1678676435998, "uuid": "759d39ef-dcc3-4013-bad5-11a33ee55a88", "historyId": "3694e86014ba970e91fd13eee1c2ee5e", "testCaseId": "db3e6fbd6ca68f97daf4eb9e50ba75ee", "fullName": "scripts.test01_mp_login.TestMpLogin#test_mp_login_error_2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "用户登录"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "wht"}, {"name": "thread", "value": "11064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01_mp_login"}]}